---
title: "testing"
output: html_document
date: "2026-02-25"
---

```{r setup, include=FALSE}

library(shiny)
library(shinyjs)
library(bslib)
library(ggplot2)
# install.packages("DT")
library(DT)
library(dplyr)
# install.packages("psych")
library(psych)
# install.packages("gtsummary")
library(gtsummary)
# install.packages("vtable")
library(vtable)
library(tidyr)
library(readr)
```

```{r}
data <- read.csv('Ass1Data.csv ',
                 stringsAsFactors = TRUE
                 )

data$Date <- as.Date(data$Date, format = "%d/%m/%Y")

data$Priority <- factor(
  data$Priority,
  levels = c("Low", "Medium", "High"),
  ordered = TRUE
)

data$Price <- factor(
  data$Price,
  levels = c("Cheap", "Fair", "Expensive"),
  ordered = TRUE
)

data$Speed <- factor(
  data$Speed,
  levels = c("Slow", "Medium", "Fast"),
  ordered = TRUE
)

data$Duration <- factor(
  data$Duration,
  levels = c("Short", "Long", "Very Long"),
  ordered = TRUE
)

data$Temp <- factor(
  data$Temp,
  levels = c("Cold", "Warm", "Hot"),
  ordered = TRUE
)


```

```{r}
row.names(data) <- data$ID
row.names(data)
data

```

```{r}

date_range <- range(data$Date)

paste('The date range in this dataset is from', date_range[1], 'to', date_range[2])
paste('Over a total of',date_range[2] - date_range[1], 'days')


```

```{r}
data %>% 
  mutate(YearMonth = floor_date(Date, "month")) %>%
  group_by(YearMonth) %>%
  summarise(Month_Count = n(), .groups = "drop") %>%
  ggplot(aes(x = YearMonth, y = Month_Count)) +
  geom_point() +
  geom_line() +

  labs(
    x = "Month",
    y = "Number of Records",
    title = "Monthly Counts Over Time"
  ) +
  theme_minimal()

```
```{r}
length(data)
```



```{r}
missing <-  round(((colSums(is.na(data)) / nrow(data)) * 100), 2)
cat(sprintf("%s: %s%%\n", names(missing), missing))

missing_df <-  data.frame(missing_percent = missing)

missing_df
```

```{r}
# for (col in colnames(Filter(is.factor, data))){
#   
#   if (col == "ID"){
#     next
#   }
# 
#   object_string <- paste("select_", tolower(col), sep = "")
#   title_string <- paste("selected_", tolower(col), sep = "")
#   
#   object <- selectizeInput(title_string, 
#                                   label = NULL,
#                                   choices = unique(data[[col]]),
#                                   multiple = TRUE,
#                                   selected = unique(data[[col]])
#   )
#   
#   assign(title_string, object)
#  
#   print(unique(data[[col]]))
# 
# }


# select_agreed <- selectizeInput("selected_agreed", 
#                                   label = NULL,
#                                   choices = unique(data$Agreed),
#                                   multiple = TRUE,
#                                   selected = unique(data$Agreed)
# )
```

```{r}
cat_vars <- data[, sapply(data, is.factor), drop =FALSE]
# cat_vars
non_cat_vars <- data[, (!sapply(data, is.factor)), drop =FALSE]
non_cat_vars
```


